[PasswordSettings]
# The minimum score required for a password to be considered valid.
#MinimumScore=10

# The maximum repeat count for any character in the password.
#MaxRepeatingCharacters=3

# Allow the use of the provided username in the password.
#AllowUsernameAsPassword=false

# The maximum repeat count for numbers in the password.
#MaxRepeatingDigits=2